dojo/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^roles/$', views.RoleView.as_view(), name='roles'),
)

kanri/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^roster/', include('roster.urls', namespace='roster')),
    url(r'^mentors/', include('mentors.urls', namespace='mentors')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^badges/', include('badges.urls', namespace='badges')),

    # Auth
    url(r'^login/', 'django.contrib.auth.views.login', name='login'),

    url(
        r'^logout/',
        'django.contrib.auth.views.logout_then_login',
        name='logout'
    ),

    # Dashboard app collects all other URLs
    url(r'', include('dashboard.urls', namespace='dashboard')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roster/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

from roster import views


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^report/', views.ReportView.as_view(), name='report'),
)

roster/models/availability.py
from django.db import models


class Availability(models.Model):
    mentor = models.ForeignKey(
        'mentors.Mentor',
        help_text='The mentor that\'s listing this availability.',
    )

    session = models.ForeignKey(
        'dojo.Session',
        help_text='The session that the mentor is available for.',
    )

    available = models.BooleanField(
        default=True,
        help_text='The mentor\'s availability for this session.',
    )

    class Meta:
        verbose_name_plural = 'Availabilities'
        ordering = ['session__start']

roster/models/shift.py
from django.db import models


class Shift(models.Model):
    mentor = models.ForeignKey(
        'mentors.Mentor',
        help_text='The mentor who is taking this shift.'
    )

    session = models.ForeignKey(
        'dojo.Session',
        help_text='The session where this shift will take place.'
    )

    role = models.ForeignKey(
        'mentors.Role',
        help_text='The role the mentor will be taking.'
    )

    start = models.DateTimeField(
        help_text='The starting time of the shift.'
    )

    finish = models.DateTimeField(
        help_text='The finishing time of the shift.'
    )

    def clean(self):
        if not self.start:
            self.start = self.session.start

        if not self.finish:
            self.finish = self.session.finish

roster/forms.py
from django import forms

from dojo import models as dojo_models


class AvailabilityReportForm(forms.Form):
    available = forms.BooleanField(
        required=False
    )

    session = forms.ModelChoiceField(
        queryset=dojo_models.Session.objects.all()
    )

roster/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from dojo import models as dojo_models
from mentors import models as mentor_models
from django.views import generic
from django.utils import timezone

import models
import forms


class ReportView(generic.View):
    def get(self, request, *args, **kwargs):
        # Get the Mentor for this user.
        mentor = mentor_models.Mentor.objects.get(user=request.user)

        relevant_sessions = dojo_models.Session.objects.filter(
            start__gt=timezone.now())

        if not self.request.user.is_superuser:
            relevant_sessions = relevant_sessions.filter(
                term__dojo__role__approved_roles=mentor,
            )

        return render(request, 'roster/availabilities/report.html', {
            'unreported_sessions': relevant_sessions.exclude(
                availability__mentor=mentor
            ),
            'reported_sessions': models.Availability.objects.filter(
                mentor=mentor,
                session__start__gt=timezone.now()
            )
        })

    def post(self, request, *args, **kwargs):
        form = forms.AvailabilityReportForm(request.POST)
        if form.is_valid():
            mentor = mentor_models.Mentor.objects.get(user=request.user)
            # Look for an existing availability for this mentor.
            try:
                avail = models.Availability.objects.get(
                    mentor=mentor,
                    session=form.cleaned_data['session']
                )
            except models.Availability.DoesNotExist:
                # couldn't find an avail,
                avail = models.Availability(
                    mentor=mentor,
                    session=form.cleaned_data['session']
                )

            avail.available = (form.cleaned_data['available'] == True)
            avail.full_clean()
            avail.save()
            messages.success(request, "Your availability for '{a.session}' "
                                      "has been updated!".format(a=avail))
            return redirect('roster:report')
        else:
            print form.errors

roster/templates/roster/availabilities/report.html
{% extends "base.html" %}

{% block site_title %}Report Availabilities{% endblock %}
{% block body_title %}Report your availabilities{% endblock %}

{% block content %}

{% if user.is_superuser %}
    <div class="alert alert-warning">
        <p>As you are a superuser, you can report availabilities for sessions at dojos that you do not attend.</p>
        <p>These sessions will be listed below.</p>
    </div>
    <hr />
{% endif %}

{% if unreported_sessions %}
    <h2>New sessions <small>that you need to report for.</small></h2>
    <table class="table">
        <thead>
            <th>Session</th>
            <th>Time/Date</th>
            <th></th>
        </thead>
        <tbody>
            {% for session in unreported_sessions %}
                <tr>
                    <td>
                        {{ session }}<br />
                           <small>{{ session.term.name }} - {{ session.term.dojo }}</small>
                    </td>
                    <td>
                        {{ session.start|date }}
            
                        {% if session.start.date != session.finish.date %}
                             - {{ session.finish|date }}
                        {% endif %}
                        <br />
                        <small>{{ session.start|time }} to {{ session.finish|time }}</small>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-success report-available" id="report-available-{{ session.id }}">Available</a>   
                            <a class="btn btn-danger report-busy" id="report-busy-{{ session.id }}">Busy</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% if reported_sessions %}
    <h2>Old sessions <small>that you've already reported for.</small></h2>
    <table class="table">
        <thead>
            <th>Session</th>
            <th>Time/Date</th>
            <th></th>
        </thead>
        <tbody>
            {% for avail in reported_sessions %}
                <tr>
                    <td>
                        {{ avail.session }}<br />
                           <small>{{ avail.session.term.name }} - {{ avail.session.term.dojo }}</small>
                    </td>
                    <td>
                        {{ avail.session.start|date }}
            
                        {% if avail.session.start.date != avail.session.finish.date %}
                             - {{ avail.session.finish|date }}
                        {% endif %}
                        <br />
                        <small>{{ avail.session.start|time }} to {{ avail.session.finish|time }}</small>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn report-available {% if avail.available %}btn-success{% else %}btn-default{% endif %}" id="report- available-{{ avail.session.id }}">Available</a>   
                            <a class="btn report-busy {% if avail.available %}btn-default{% else %}btn-danger{% endif %}" id="report-busy-{{ avail.session.id }}">Busy</a>   
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

<form class="hidden" id="available-form" method="post" action="{% url 'roster:report' %}">
    {% csrf_token %}
    <input type="text" name="session" id="id_session" />
    <input type="checkbox" name="available" id="id_available" checked />
</form>
{% endblock %}

{% block custom_js %}
<script type='text/javascript'>
    function report(ev, available)
    {
        $('#id_session').val(ev.target.id.replace(/report-.+-/, ''))
        $('#id_available').prop('checked', available)

        $('#available-form').submit()
    }

    function report_available(ev)
    {
        report(ev, true)
    }

    function report_busy(ev)
    {
        report(ev, false)
    }

    $('.report-available').click(report_available)
    $('.report-busy').click(report_busy)
</script>
{% endblock %}